name: Scheduled Trigger

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)

jobs:
  trigger-manual-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Manual Action
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "run-manual-action"}'
